import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :pulsarius, PulsariusWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :rollbax,
  enabled: true,
  enable_crash_reports: true


 stripe_api_key =
    System.get_env("STRIPE_API_KEY") ||
      raise """
      environment variable STRIPE_API_KEY is missing.
      You can obtain it from the stripe dashboard: https://dashboard.stripe.com/test/apikeys
      """

  stripe_webhook_key =
    System.get_env("STRIPE_WEBHOOK_SIGNING_SECRET") ||
      raise """
      environment variable STRIPE_WEBHOOK_SIGNING_SECRET is missing.
      You can obtain it from the stripe dashboard: https://dashboard.stripe.com/account/webhooks
      """

  stripe_public_key =
    System.get_env("STRIPE_PUBLIC_KEY") ||
      raise """
      environment variable STRIPE_PUBLIC_KEY is missing.
      You can obtain it from the stripe dashboard: https://dashboard.stripe.com/account/webhooks
      """

  config :stripity_stripe,
    api_key: stripe_api_key,
    signing_secret: stripe_webhook_key,
    public_key: stripe_public_key

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :pulsarius, PulsariusWeb.Endpoint,
#       ...,
#       url: [host: "example.com", port: 443],
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :pulsarius, PulsariusWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.
